pipeline:
  # test_node18:
  #   image: node:18
  #   pull: true
  #   secrets: [infura_project_id, alchemy_api_key, etherscan_api_key]
  #   commands:
  #     - apt update
  #     - apt install xxd
  #     - node -v
  #     - npm -v
  #     - npm ci
  #     - npm run build
  #     - npm -g install .
  #     - npm test
  #   when:
  #     ref: refs/tags/v*

  test_node16:
    image: node:16
    pull: true
    secrets: [infura_project_id, alchemy_api_key, etherscan_api_key]
    commands:
      - apt update
      - apt install xxd
      - node -v
      - npm -v
      - npm ci
      - npm run build
      - npm -g install .
      - npm test
    when:
      ref: refs/tags/v*

  test_node14:
    image: node:14
    pull: true
    secrets: [infura_project_id, alchemy_api_key, etherscan_api_key]
    commands:
      - apt update
      - apt install xxd
      - npm i -g npm@8
      - node -v
      - npm -v
      - npm ci
      - npm run build
      - npm -g install .
      - npm test
    when:
      ref: refs/tags/v*

  test_node12:
    image: node:12
    pull: true
    secrets: [infura_project_id, alchemy_api_key, etherscan_api_key]
    commands:
      - apt update
      - apt install xxd
      - npm i -g npm@8
      - node -v
      - npm -v
      - npm ci
      - npm run build
      - npm -g install .
      - npm test

  publish_npm:
    image: plugins/npm
    secrets: [npm_token]
    username: iexecteam
    email: dev@iex.ec
    tag: latest
    when:
      ref:
        include: refs/tags/v[1-9]*.*[0-9].*[0-9]
        exclude: refs/tags/v[1-9]*.*[0-9].*[0-9]-*

  publish_alpha_npm:
    image: plugins/npm
    secrets: [npm_token]
    username: iexecteam
    email: dev@iex.ec
    tag: alpha
    when:
      ref: refs/tags/v[1-9]*.*[0-9].*[0-9]-alpha.*[0-9]

  publish_dockerhub:
    image: plugins/docker
    repo: iexechub/iexec-sdk
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - ${DRONE_TAG##v}
    when:
      ref:
        include: refs/tags/v[1-9]*.*[0-9].*[0-9]
        exclude: refs/tags/v[1-9]*.*[0-9].*[0-9]-*

services:
  token-chain:
    image: iexechub/poco-chaintest:5.3.2-token
    pull: true

  native-chain:
    image: iexechub/poco-chaintest:5.3.2-native
    pull: true

  token-chain-1s:
    image: iexechub/poco-chaintest:5.3.2-token
    command: '--miner.blockTime 1'
    pull: true

  token-chain-openethereum:
    image: iexechub/poco-chaintest:5.3.2-token-openethereum
    pull: true

  token-sms:
    image: iexechub/iexec-sms:7.1.0
    pull: true
    environment:
      - TZ=Europe/Paris
      - IEXEC_SMS_BLOCKCHAIN_NODE_ADDRESS=http://token-chain-openethereum:8545
      - IEXEC_HUB_ADDRESS=0xC129e7917b7c7DeDfAa5Fff1FB18d5D7050fE8ca
      - IEXEC_TEE_WORKER_PRE_COMPUTE_IMAGE=docker.io/iexechub/tee-worker-pre-compute:7.1.0-sconify-5.3.15-debug
      - IEXEC_TEE_WORKER_PRE_COMPUTE_FINGERPRINT=9f0f782d6edc611baa23ca0978f555ee58ea70e092640c961e75c25e9e4b0f22
      - IEXEC_TEE_WORKER_PRE_COMPUTE_HEAP_SIZE_GB=4
      - IEXEC_TEE_WORKER_POST_COMPUTE_IMAGE=docker.io/iexechub/tee-worker-post-compute:7.1.1-sconify-5.3.15-debug
      - IEXEC_TEE_WORKER_POST_COMPUTE_FINGERPRINT=face1376b97131e2dc75a556381d47a2e03bed9e1bc11e462471f99d1eefae50
      - IEXEC_TEE_WORKER_POST_COMPUTE_HEAP_SIZE_GB=4
      - IEXEC_IGNORED_SGX_ADVISORIES=INTEL-SA-00161,INTEL-SA-00289,INTEL-SA-00334,INTEL-SA-00381,INTEL-SA-00389,INTEL-SA-00220,INTEL-SA-00270,INTEL-SA-00293,INTEL-SA-00320,INTEL-SA-00329,INTEL-SA-00477
      - IEXEC_SCONE_TOLERATED_INSECURE_OPTIONS=debug-mode,hyperthreading,outdated-tcb
      - IEXEC_SMS_DISPLAY_DEBUG_SESSION=true
      - IEXEC_SCONE_CAS_HOST=foo
      - IEXEC_SMS_IMAGE_LAS_IMAGE=foo
    expose:
      - 13300
    depends_on:
      - token-chain-openethereum

  token-result-proxy:
    image: iexechub/iexec-result-proxy:7.1.0
    pull: true
    environment:
      - IEXEC_PRIVATE_CHAIN_ADDRESS=http://token-chain-openethereum:8545
      - IEXEC_PUBLIC_CHAIN_ADDRESS=http://token-chain-openethereum:8545
      - IEXEC_HUB_ADDRESS=0xC129e7917b7c7DeDfAa5Fff1FB18d5D7050fE8ca
      - MONGO_HOST=token-result-proxy-mongo
      - MONGO_PORT=13202
      - IEXEC_IPFS_HOST=ipfs
    expose:
      - 13200
    depends_on:
      - token-chain-openethereum
      - token-result-proxy-mongo
      - ipfs

  token-result-proxy-mongo:
    pull: true
    image: library/mongo:4.2
    entrypoint: '/bin/bash'
    command: -c "mongod --bind_ip_all --port 13202"
    expose:
      - 13202

  ipfs:
    image: ipfs/go-ipfs:v0.9.1
    pull: true

  gateway-mongo:
    image: mongo:latest

  gateway-redis:
    image: redis:alpine
    command: redis-server --appendonly yes

  token-watcher:
    image: iexechub/iexec-market-watcher:5
    commands:
      - sleep 10
      - cd /app
      - npm start
    environment:
      - DEBUG=iexec-watcher*
      - DEBUG_COLORS=true
      - CHAIN=DEV
      - CHAIN_ID=65535
      - IEXEC_ADDRESS=0xC129e7917b7c7DeDfAa5Fff1FB18d5D7050fE8ca
      - ETH_WS_HOST=ws://token-chain-openethereum:8546
      - ETH_RPC_HOST=http://token-chain-openethereum:8545
      - MONGO_HOST=gateway-mongo
      - REDIS_HOST=gateway-redis

  token-gateway:
    image: iexechub/iexec-market-api:5
    commands:
      - sleep 10
      - cd /app
      - npm start
    environment:
      - DEBUG=iexec-market-api*
      - DEBUG_COLORS=true
      - CHAINS=DEV
      - DEV_NATIVE=false
      - DEV_ETH_RPC_HOST=http://token-chain-openethereum:8545
      - DEV_CHAIN_ID=65535
      - DEV_IEXEC_ADDRESS=0xC129e7917b7c7DeDfAa5Fff1FB18d5D7050fE8ca
      - MONGO_HOST=gateway-mongo
      - REDIS_HOST=gateway-redis
      - RATE_LIMIT_MAX=10000
      - RATE_LIMIT_PERIOD=60000
      - MAX_OPEN_ORDERS_PER_WALLET=1000
