---
kind: pipeline
type: docker
name: publish nightly

trigger:
  event:
    - promote
  target:
    - nightly
  branch:
    - next
    - new

steps:
  - name: install
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: build
    image: node:18
    commands:
      - npm run build
    depends_on:
      - install

  - name: format
    image: node:18.19
    commands:
      - npm run check-format
    depends_on:
      - build

  - name: lint
    image: node:18.19
    commands:
      - npm run lint
    depends_on:
      - build

  - name: set-version-nightly
    image: node:18
    commands:
      - eval npm pkg set version="$(npm pkg get version)-nightly-$DRONE_COMMIT"

  - name: npm publish
    image: plugins/npm
    pull: always
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token
      tag: ${DRONE_BRANCH}
    depends_on:
      - format
      - lint
      - build
      - set-version-nightly

  - name: docker publish
    image: plugins/docker
    pull: always
    settings:
      registry: docker-regis.iex.ec
      repo: docker-regis.iex.ec/iexec-sdk
      dockerfile: Dockerfile
      username:
        from_secret: nexus-user
      password:
        from_secret: nexus-password
      tags:
        - ${DRONE_BRANCH}
        - ${DRONE_BRANCH}-${DRONE_COMMIT}

---
kind: pipeline
type: docker
name: publish latest

# promote latest on tag semver tags
trigger:
  event:
    - promote
  target:
    - latest
  ref:
    include:
      - refs/tags/v[0-9]*.*[0-9].*[0-9]
    exclude:
      - refs/tags/v*.*.*.*
      - refs/tags/v*-*
      - refs/tags/v*[a-zA-Z]*

steps:
  - name: install
    image: node:18
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: build
    image: node:18
    commands:
      - npm run build
    depends_on:
      - install

  - name: format
    image: node:18.19
    commands:
      - npm run check-format
    depends_on:
      - build

  - name: lint
    image: node:18.19
    commands:
      - npm run lint
    depends_on:
      - build

  - name: npm publish
    image: plugins/npm
    pull: always
    settings:
      username:
        from_secret: npm_username
      token:
        from_secret: npm_token
      tag: latest
    depends_on:
      - format
      - lint
      - build

  - name: docker publish
    image: plugins/docker
    pull: always
    settings:
      repo: iexechub/iexec-sdk
      dockerfile: Dockerfile
      tags:
        - latest
        - ${DRONE_TAG##v}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
