#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="postinst"
LOG="/var/log/xwhep-client.log"
INSTALLDIR="/opt/xwhep-client-10.5.2"
XW_BINDIR="$INSTALLDIR/bin"
PROG="xwhep.client"
USRBIN="/usr/bin"

touch $LOG
date >> $LOG  2>&1 
echo "XtremWeb-HEP $PROG $WHAT 10.5.2" >> $LOG  2>&1 

ln -fs $XW_BINDIR/xwalive $USRBIN
ln -fs $XW_BINDIR/xwdownload $USRBIN
ln -fs $XW_BINDIR/xwusergroups $USRBIN
ln -fs $XW_BINDIR/xwapps $USRBIN
ln -fs $XW_BINDIR/xwgroups $USRBIN
ln -fs $XW_BINDIR/xwusers $USRBIN
ln -fs $XW_BINDIR/xwgroupworks $USRBIN
ln -fs $XW_BINDIR/xwsendapp $USRBIN
ln -fs $XW_BINDIR/xwstatus $USRBIN
ln -fs $XW_BINDIR/xwgui $USRBIN
ln -fs $XW_BINDIR/xwsenddata $USRBIN
ln -fs $XW_BINDIR/xwsendgroup $USRBIN
ln -fs $XW_BINDIR/xwsubmit $USRBIN
ln -fs $XW_BINDIR/xwversion $USRBIN
ln -fs $XW_BINDIR/xwchmod $USRBIN
ln -fs $XW_BINDIR/xwsendsession $USRBIN
ln -fs $XW_BINDIR/xwtasks $USRBIN
ln -fs $XW_BINDIR/xwclean $USRBIN
ln -fs $XW_BINDIR/xwsenduser $USRBIN
ln -fs $XW_BINDIR/xwworkers $USRBIN
ln -fs $XW_BINDIR/xwclient $USRBIN
ln -fs $XW_BINDIR/xwsendusergroup $USRBIN
ln -fs $XW_BINDIR/xwworks $USRBIN
ln -fs $XW_BINDIR/xwping $USRBIN
ln -fs $XW_BINDIR/xwsendwork $USRBIN
ln -fs $XW_BINDIR/xwresults $USRBIN
ln -fs $XW_BINDIR/xwsessions $USRBIN
ln -fs $XW_BINDIR/xwdatas $USRBIN
ln -fs $XW_BINDIR/xwrm $USRBIN


echo "XtremWeb-HEP $PROG $WHAT done " >> $LOG  2>&1 
