#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="postrm"
LOG="/var/log/xwhep-client.log"
INSTALLDIR="/opt/xwhep-client-10.5.2"
BINDIR="$INSTALLDIR/bin"
PROG="xwhep.client"
USRBIN=/usr/bin

touch $LOG
date >> $LOG  2>&1 
echo "XtremWeb-HEP $PROG $WHAT 10.5.2 " >> $LOG  2>&1 

rm -f $USRBIN/xwalive
rm -f $USRBIN/xwdownload
rm -f $USRBIN/xwusergroups
rm -f $USRBIN/xwapps
rm -f $USRBIN/xwgroups
rm -f $USRBIN/xwusers
rm -f $USRBIN/xwgroupworks
rm -f $USRBIN/xwsendapp
rm -f $USRBIN/xwstatus
rm -f $USRBIN/xwgui
rm -f $USRBIN/xwsenddata
rm -f $USRBIN/xwsendgroup
rm -f $USRBIN/xwsubmit
rm -f $USRBIN/xwversion
rm -f $USRBIN/xwchmod
rm -f $USRBIN/xwsendsession
rm -f $USRBIN/xwtasks
rm -f $USRBIN/xwclean
rm -f $USRBIN/xwsenduser
rm -f $USRBIN/xwworkers
rm -f $USRBIN/xwclient
rm -f $USRBIN/xwsendusergroup
rm -f $USRBIN/xwworks
rm -f $USRBIN/xwping
rm -f $USRBIN/xwsendwork
rm -f $USRBIN/xwresults
rm -f $USRBIN/xwsessions
rm -f $USRBIN/xwdatas
rm -f $USRBIN/xwrm

rm -Rf $INSTALLDIR >> $LOG 2>&1

echo "XtremWeb-HEP $PROG $WHAT done" >> $LOG  2>&1 
