#!/bin/sh

# Copyrights     : CNRS
# Author         : Oleg Lodygensky
# Acknowledgment : XtremWeb-HEP is based on XtremWeb 1.8.0 by inria : http://www.xtremweb.net/
# Web            : http://www.xtremweb-hep.org
# 
#      This file is part of XtremWeb-HEP.
#
#    XtremWeb-HEP is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    XtremWeb-HEP is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with XtremWeb-HEP.  If not, see <http://www.gnu.org/licenses/>.


LOGDATE=`date "+%Y%m%d%H%M%S"`
WHAT="preinst"
LOG="/var/log/xwhep-client.log"
XW_INSTALLDIR="/opt/xwhep-client-10.5.2"
BINDIR="$INSTALLDIR/bin"
PROG="xwhep.client"

touch $LOG
date >> $LOG  2>&1 
echo "XtremWeb-HEP $PROG $WHAT 10.5.2" >> $LOG  2>&1 

rm -Rf $XW_INSTALLDIR  >> $LOG  2>&1
mkdir -p $XW_INSTALLDIR  >> $LOG  2>&1
cd $XW_INSTALLDIR  >> $LOG  2>&1
echo "XtremWeb-HEP $PROG $WHAT done" >> $LOG  2>&1 
