FROM trufflesuite/ganache-cli:latest

COPY ./ganachedb /ganachedb

CMD ["-m", "actual surround disorder swim upgrade devote digital misery truly verb slide final", "-l", "8000000", "-i", "65535", "--hardfork", "istanbul", "--db", "/ganachedb"]
