FROM trufflesuite/ganache-cli:latest

COPY ./ganachedb_bkp /ganachedb

CMD ["-m", "actual surround disorder swim upgrade devote digital misery truly verb slide final", "-l", "8000000", "-i", "1544020727674", "--db", "/ganachedb"]
