name: Conventional Commit Check Commits

on: [pull_request]

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Commit Conventions
        uses: webiny/action-conventional-commits@v1.3.0
