name: docker publish staging
# Publish a staging version on docker registry

on:
  workflow_dispatch:

permissions: {}

jobs:
  compute-staging-version:
    uses: ./.github/workflows/reusable-compute-staging-version.yml
    permissions:
      contents: read

  docker-publish:
    uses: ./.github/workflows/reusable-docker.yml
    permissions:
      contents: read
      id-token: write
      attestations: write
    needs: compute-staging-version
    with:
      tag: ${{ needs.compute-staging-version.outputs.version }}
    secrets:
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker-password: ${{ secrets.DOCKERHUB_PAT }}
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN_PULL_ONLY }}
