name: docker publish staging
description: Publish a staging version on docker registry

on:
  workflow_dispatch:

jobs:
  compute-staging-version:
    uses: ./.github/workflows/reusable-compute-staging-version.yml

  docker-publish:
    uses: ./.github/workflows/reusable-docker.yml
    needs: compute-staging-version
    with:
      tag: ${{ needs.compute-staging-version.outputs.version }}
    secrets:
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
