name: Test SDK

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: graphnode
          POSTGRES_PASSWORD: password
          POSTGRES_DB: graphnode-db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      ipfs:
        image: ipfs/kubo:v0.17.0
        ports:
          - 5001:5001
      graphnode:
        image: graphprotocol/graph-node:latest
        env:
          - IPFS: ipfs:5001
          - POSTGRES_HOST: postgres
          - POSTGRES_USER: graphnode
          - POSTGRES_DB: graphnode-db
          - POSTGRES_PASSWORD: password
          - ETHEREUM: bellecour:http://localhost:8545
        ports:
          - 8000:8000
          - 8020:8020
      steps:
        - uses: actions/checkout@v4
        - uses: actions/nodejs@v4
          with:
            node-version: '18'
        - name: Prepare
          run: node test/scripts/prepare-test-env.js
        - name: Test
          run: npm test

        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
          with:
            version: stable
            cache: true

        - name: Start Anvil
          uses: iExecBlockchainComputing/anvil-github-action@main
          with:
            anvil-port: "8545"
            block-time: "1"
            hardfork: "berlin"
            chain-id: "134"
            gas-limit: "6700000"
            gas-price: "0"

        - name: Start MongoDB
          uses: supercharge/mongodb-github-action@1.12.0
          with:
            mongodb-version: '6.0'

        - name: Start Redis
          uses: supercharge/redis-github-action@1.7.0
          with:
            redis-version: '7'

