name: npm publish latest
description: Publish on npm when a release is published

on:
  release:
    types: [published]

jobs:
  npm-publish:
    uses: ./.github/workflows/reusable-npm.yml
    with:
      tag: 'latest'
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
