name: npm publish latest
description: Publish on npm when a release is published

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  packages: write
  contents: read

jobs:
  npm-publish:
    uses: ./.github/workflows/reusable-npm.yml
    with:
      tag: "latest"
