name: npm publish

on:
    # For staging releases
    workflow_dispatch:
    # For latest releases
    release:
        types: [published]

permissions:
    id-token: write # Required for OIDC
    packages: write
    contents: read

jobs:
    compute-staging-version:
        # Only run for manual dispatch (staging)
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/workflows/reusable-compute-staging-version.yml

    npm-publish-staging:
        # Only run for manual dispatch (staging)
        if: github.event_name == 'workflow_dispatch'
        uses: ./.github/workflows/reusable-npm.yml
        needs: [compute-staging-version]
        with:
            version: ${{ needs.compute-staging-version.outputs.version }}
            tag: ${{ needs.compute-staging-version.outputs.dist-tag }}

    npm-publish-latest:
        # Only run for release published (latest)
        if: github.event_name == 'release'
        uses: ./.github/workflows/reusable-npm.yml
        with:
            tag: latest
