name: npm publish staging
description: Publish a staging version on npm

on:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  packages: write
  contents: read

jobs:
  compute-staging-version:
    uses: ./.github/workflows/reusable-compute-staging-version.yml

  npm-publish:
    uses: ./.github/workflows/reusable-npm.yml
    needs: compute-staging-version
    with:
      version: ${{ needs.compute-staging-version.outputs.version }}
      tag: ${{ needs.compute-staging-version.outputs.dist-tag }}
