name: PR test

on: [pull_request]

permissions:
  # Allows the workflow to write pull request comments (required for dependabot in docker-dry-run job)
  # https://docs.github.com/en/code-security/dependabot/troubleshooting-dependabot/troubleshooting-dependabot-on-github-actions#changing-github_token-permissions
  pull-requests: write
  # permissions for build
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}-pr-test
  cancel-in-progress: true

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npm run codegen

      - name: Check format
        run: npm run check-format

      - name: Lint
        run: npm run lint

  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      node-version: '20'

  test-supported-node-versions:
    uses: ./.github/workflows/reusable-test.yml
    # for release PR run tests on all supported node versions
    if: startsWith(github.head_ref,'release-please--')
    strategy:
      matrix:
        node-version: ['22', '24']
    with:
      node-version: ${{ matrix.node-version }}

  npm-dry-run:
    uses: ./.github/workflows/reusable-npm.yml
    with:
      dry-run: true

  docker-dry-run:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      dry-run: true
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PAT }}
