name: release-please
# triggers release-please to open the next release PR

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/release-please.yml@8bf223e4a6b5e88d42f9c91e57dcfd31d1cb0e5a # release-please-v2.2.2
    secrets: inherit
