name: test SDK

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to use as specified in actions/setup-node'
        default: '20'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npm run

      - name: Build
        run: npm run build

      - name: Install global
        run: npm install -g .

      - name: Start e2e test stack
        run: npm run start-test-stack

      - name: Test
        run: npm test
        env:
          USE_LOCAL_CLI: true

      - name: Stop e2e test stack
        if: always()
        run: npm run stop-test-stack
