name: Compute staging version
description: compute a staging version from the current version, branch name and commit

on:
  workflow_call:
    outputs:
      version:
        description: 'Coverage artifact id (if `upload-coverage: true`)'
        value: ${{ jobs.compute-staging-version.outputs.version }}
      dist-tag:
        value: ${{ jobs.compute-staging-version.outputs.dist-tag }}

jobs:
  compute-staging-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Set publish version
        id: set-publish-version
        run: |
          BRANCH=$(echo "${{ github.ref_name }}" | sed 's|/|-|g')
          CURRENT_VERSION=$(npm pkg get version | tr -d '"')
          STAGING_VERSION="${CURRENT_VERSION}-${BRANCH}-${GITHUB_SHA::7}"
          echo "VERSION=${STAGING_VERSION}" >> $GITHUB_OUTPUT
          echo "DIST_TAG=${BRANCH}" >> $GITHUB_OUTPUT
          echo "VERSION=${STAGING_VERSION}"
          echo "DIST_TAG=${BRANCH}"
    outputs:
      version: ${{ steps.set-publish-version.outputs.VERSION }}
      dist-tag: ${{ steps.set-publish-version.outputs.DIST_TAG }}
