FROM iexechub/poco-chaintest:v5-token

CMD ["-m", "actual surround disorder swim upgrade devote digital misery truly verb slide final", "--blockTime", "1", "-l", "8000000", "-i", "1544020727674", "--db", "/ganachedb"]
